version: '3.8'
services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_USER:-dev_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data/

networks:
  broker-kafka:
    driver: bridge
volumes:
  postgres-data:
    driver: local